### ISSUE TITLE
I don't know where the mod list is located

### ISSUE THREAD

**Issue by kierkat10** [ZedDevStuff/ModList#1]
simple as that @ZedDevStuff

**Comment by ZedDevStuff** [comment]
> simple as that @ZedDevStuff 

When you open the game in the main menu, bottom left corner

**Comment by kierkat10** [comment]
I don't see it. Let me check my mods to see if any are overriding it or something.

**Comment by kierkat10** [comment]
Are there any mods needed for it to function? Loading the game without any mods except for ModList still does not show anything. @ZedDevStuff

**Comment by ZedDevStuff** [comment]
> Are there any mods needed for it to function? Loading the game without any mods except for ModList still does not show anything. @ZedDevStuff 

It's supposed to just work. Can you change your game resolution to 1600x900 and see if it appears? If it does, I might have messed up

**Comment by kierkat10** [comment]
let's see

**Comment by kierkat10** [comment]
it simply just ain't showing up for me

**Comment by kierkat10** [comment]
i'm going to do some testing myself

**Comment by kierkat10** [comment]
r2modman doesn't fix anything, restarted my computer, put the file in different spots (and the folder), redownloaded twice, looked through logs, it ain't working.

**Comment by kierkat10** [comment]
the ultrakill logs act as if there isn't a mod and the bepinex logs don't give much info and just say "Plugin ModList is loaded!"

**Comment by kierkat10** [comment]
might have to close this as not planned since i have no clue why it's not working @ZedDevStuff

**Comment by ZedDevStuff** [comment]
> might have to close this as not planned since i have no clue why it's not working @ZedDevStuff 

So I think I found about the issue. Since patch 15, BepInEx acts inconsistently. To fix that you need to open the BepInEx.cfg file in either your r2modman profile directory (you can go there from r2modman settings) and change `HideManagerGameObject = false` to `true`

To be honest this issue breaks a lot of mods too. It's even pinned in the ULTRAKILL discord server's modding channel

**Comment by kierkat10** [comment]
yeah it works now! thanks!

**Comment by kierkat10** [comment]
oh also, why would the icon for a mod not show up? I have it installed with the icon.

**Comment by kierkat10** [comment]
nevermind, some mods just don't like to show their icons which is weird
